# Generated by Django 5.1.2 on 2024-11-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
    ]
