# Generated by Django 5.1.3 on 2024-11-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_eventlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
