# Generated by Django 5.1.3 on 2025-03-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
