# Generated by Django 5.1.3 on 2025-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_compliancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
